labels:
  0: 'noise'
  1: 'animal'
  2: 'human.pedestrian.adult'
  3: 'human.pedestrian.child'
  4: 'human.pedestrian.construction_worker'
  5: 'human.pedestrian.personal_mobility'
  6: 'human.pedestrian.police_officer'
  7: 'human.pedestrian.stroller'
  8: 'human.pedestrian.wheelchair'
  9: 'movable_object.barrier'
  10: 'movable_object.debris'
  11: 'movable_object.pushable_pullable'
  12: 'movable_object.trafficcone'
  13: 'static_object.bicycle_rack'
  14: 'vehicle.bicycle'
  15: 'vehicle.bus.bendy'
  16: 'vehicle.bus.rigid'
  17: 'vehicle.car'
  18: 'vehicle.construction'
  19: 'vehicle.emergency.ambulance'
  20: 'vehicle.emergency.police'
  21: 'vehicle.motorcycle'
  22: 'vehicle.trailer'
  23: 'vehicle.truck'
  24: 'flat.driveable_surface'
  25: 'flat.other'
  26: 'flat.sidewalk'
  27: 'flat.terrain'
  28: 'static.manmade'
  29: 'static.other'
  30: 'static.vegetation'
  31: 'vehicle.ego'
labels_16:
  0: 'noise'
  1: 'barrier'
  2: 'bicycle'
  3: 'bus'
  4: 'car'
  5: 'construction_vehicle'
  6: 'motorcycle'
  7: 'pedestrian'
  8: 'traffic_cone'
  9: 'trailer'
  10: 'truck'
  11: 'driveable_surface'
  12: 'other_flat'
  13: 'sidewalk'
  14: 'terrain'
  15: 'manmade'
  16: 'vegetation'
# learning_map:
#   1: 0
#   5: 0
#   7: 0
#   8: 0
#   10: 0
#   11: 0
#   13: 0
#   19: 0
#   20: 0
#   0: 0
#   29: 0
#   31: 0
#   9: 1
#   14: 2
#   15: 3
#   16: 3
#   17: 4
#   18: 5
#   21: 6
#   2: 7
#   3: 7
#   4: 7
#   6: 7
#   12: 8
#   22: 9
#   23: 10
#   24: 11
#   25: 12
#   26: 13
#   27: 14
#   28: 15
#   30: 16

learning_map:
  0: 45
  1: 46
  2: 47
  3: 37
  4: 9
  5: 70
  6: 9
  7: 0
  8: 0
  9: 79
  10: 0
  11: 0
  12: 39
  13: 0
  14: 3
  15: 4
  16: 4
  17: 2
  18: 8
  19: 8
  20: 8
  21: 5
  22: 8
  23: 7
  24: 12
  25: 15
  26: 14
  27: 15
  28: 16
  29: 83
  30: 20
  31: 0