labels:
  0: unlabeled
  1: car 
  2: pick-up
  3: truck 
  4: bus 
  5: bicycle 
  6: motorcycle 
  7: other-vehicle 
  8: road 
  9: sidewalk 
  10: parking 
  11: other-ground 
  12: female 
  13: male 
  14: kid 
  15: crowd 
  16: bicyclist
  17: motorcyclist 
  18: building 
  19: other-structure 
  20: vegetation
  21: trunk
  22: terrain 
  23: traffic-sign 
  24: pole 
  25: traffic-cone 
  26: fence 
  27: garbage-can
  28: electric-box 
  29: table 
  30: chair 
  31: bench 
  32: other-object

ignored_label: 0 
  


learning_map:
  0: 0
  1: 2
  2: 34
  3: 7
  4: 4
  5: 3
  6: 5
  7: 8
  8: 12
  9: 14
  10: 13
  11: 15
  12: 35
  13: 36
  14: 37
  15: 38
  16: 10
  17: 11
  18: 16
  19: 18
  20: 20
  21: 21
  22: 22
  23: 24
  24: 23
  25: 39
  26: 17
  27: 40
  28: 41
  29: 42
  30: 43
  31: 44
  32: 25

split: # no validation and test because this lidar dataset only train with 
  train: # sequence numbers
    - 00
    - 01
    - 02
    - 03
    - 04
    - 05
    - 06
    - 07
    - 09
    - 10
    - 11
    - 12

  valid : 
    - 08

  test: 
    - 08