# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "cylinder_asym"

  output_shape:
    - 480
    - 360
    - 32

  fea_dim: 9
  out_fea_dim: 128 #256
  num_class: 83
  num_input_features: 16
  use_norm: True
  init_size: 16 #32


###################
## Dataset options
dataset_params:
  dataset_type: "cylinder_dataset"
  pc_dataset_type: "SemKITTI_sk"
  ignore_label: 0
  return_test: False
  fixed_volume_space: True
  label_mapping: "./config/label_mapping/nuscenes.yaml"
  max_volume_space:
    - 50
    - 3.1415926
    - 3
  min_volume_space:
    - 0
    - -3.1415926
    - -5


###################
## Data_loader options
train_data_loader:
  data_path: "/dataset/nuscenes_kitti_real/"
  imageset: "train"
  return_ref: True
  batch_size: 1 #2
  shuffle: True
  num_workers: 12 #4

val_data_loader:
  data_path: "/dataset/nuscenes_kitti_real/"
  imageset: "val"
  return_ref: True
  batch_size: 1 #1
  shuffle: False
  num_workers: 12 #4


###################
## Train params
train_params:
  model_load_path: "./model_load_dir_nuscenes/model_true_half_75_7.pt" #model_load_nuscenes.pt"
  model_save_path: "./model_save_dir_nuscenes/model_true_half_finetune.pt"
  checkpoint_every_n_steps: 4599
  max_num_epochs: 40
  eval_every_n_steps: 4599
  learning_rate: 0.002 #1
